wifi.sta.eventMonReg(wifi.STA_IDLE, function() end)
wifi.sta.eventMonReg(wifi.STA_WRONGPWD, function()
    log("EvMon: WRONGPWD")
    flash(lRed,1000)
end)
wifi.sta.eventMonReg(wifi.STA_APNOTFOUND, function()
    log("EvMon: APNOTFOUND")
    flash(lRed,1000)
end)
wifi.sta.eventMonReg(wifi.STA_FAIL, function()
    log("EvMon: FAIL")
    flash(lRed,1000)
end)
wifi.sta.eventMonReg(wifi.STA_CONNECTING, function()
    log("EvMon: CONNECTING")
    flash(lBlu,1000)
end)
wifi.sta.eventMonReg(wifi.STA_GOTIP, function()
    log("EvMon: GOTIP")
    log('{ "Mode":"'..wifi.getmode()..'", "MAC":"'..wifi.ap.getmac()..'", "IP":"'..wifi.sta.getip()..'", "CH":"'..wifi.getchannel()..'" }')
    flash(lGrn,1000)
end)

wifi.sta.eventMonStart()
